#!/bin/bash
echo "Compiling the Device Tree Overlay"
dtc -O dtb -I dts -o /lib/firmware/DTO-00A0.dtbo -b 0 -@ DTO.dts

echo DTO > /sys/devices/bone_capemgr.9/slots
cat /sys/devices/bone_capemgr.?/slots